# Generated by Django 5.0.6 on 2024-06-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('eng_title', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('m_type', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=1000, null=True)),
                ('enter_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('m_d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.director')),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'moviedirector',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_type', models.CharField(blank=True, max_length=100, null=True)),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'genre',
                'unique_together': {('g_id', 'm')},
            },
        ),
    ]
